In [1]:
import pandas as pd

In [3]:
pd.read_csv('p2_apr_4_5_2022.csv')

     4/4/22  51:16.9  1.30370702
0    4/4/22  51:46.9    0.975526
1    4/4/22  52:17.0    0.847721
2    4/4/22  52:47.0    0.783494
3    4/4/22  53:17.2    0.844758
4    4/4/22  53:47.2    0.650030
..      ...      ...         ...
350  4/5/22  48:31.7    0.786531
351  4/5/22  49:07.0    0.728415
352  4/5/22  49:42.2    0.746189
353  4/5/22  50:17.4    0.736761
354  4/5/22  50:52.7    0.655244

[355 rows x 3 columns]